### ISSUE TITLE
Bot token should not be in code

### ISSUE THREAD

**Issue by jacobsandersen** [bluemustard2/quote-bot#1]
https://github.com/bluemustard2/quote-bot/blob/22c28c630d6d011ddc55f23a7e4bf82eb2e5c894/src/main/java/com/github/bluemustard2/Main.java#L26

Change to `System.getenv("QUOTE_BOT_TOKEN")` then when you run the app, run it as `QUOTE_BOT_TOKEN=<token> java -jar /path/to/jarfile.jar`.

**Comment by bluuto** [comment]
Thank you! Beginner mistake.

**Comment by jacobsandersen** [comment]
Fixed in [this commit](https://github.com/bluemustard2/quote-bot/commit/a4b5dd70a83ad2f6b274a4aaec5760167f765d1a)
